### PR TITLE
Removed unwanted arguments and parametres

### LINKED ISSUE #112: Remove `cfg` and `config` from `PrintListImages()`
There are two unused parameters `cfg` and `config` in the `PrintListImages()` function under `pkg/service/list_images.go`.
Since these are unused, it would be better to remove them from the function.

/good-first-issue

### PR DESCRIPTION
**Pull request by BalaadityaPatanjali**
Fixes #112

### CODE REVIEW

**Review by rakshitgondwal — APPROVED** [review]
lgtm, let's wait for a maintainer to review this. thanks!

**Review by rakshitgondwal — COMMENTED** [review]
@BalaadityaPatanjali you need to remove unused dependencies.

**Comment by rjsadow** [comment]
/approve
/lgtm

Thank you for the contribution @BalaadityaPatanjali 
Thank you for your help @rakshitgondwal

**Pull request merged**
