### PR TITLE
feat: SecurityContexts to fullfill PodSecurity policy baseline

### PR DESCRIPTION
**Pull request by camaeel**
SecurityContexts to fullfill PodSecurity policy baseline.

Adds containers securityContext settings.

Fixes: #217

### CODE REVIEW

**Comment by camaeel** [comment]
e2e test run with kind was successful:
```
Ginkgo ran 1 suite in 1h48m45.314845655s
Test Suite Passed
2024/10/18 21:01:41 Saving results at /tmp/results
23:01:41 INF Tests finished after 1h48m38s.
23:01:41 INF Downloading e2e.log to /Users/kamil/src/github.com/camaeel/hydrophone/_artifacts/results/e2e.log...
23:01:42 INF Downloading junit_01.xml to /Users/kamil/src/github.com/camaeel/hydrophone/_artifacts/results/junit_01.xml...
23:01:42 INF Waiting for Pod to terminate...
23:01:42 INF Container conformance-container terminated.
23:01:42 INF Deleted ClusterRoleBinding conformance-serviceaccount-role:conformance.
23:01:42 INF Deleted ClusterRole conformance-serviceaccount:conformance.
23:01:42 INF Waiting for Namespace conformance to be deleted.
23:02:20 INF Deleted Namespace conformance.
23:02:20 INF Tests completed successfully.
+ [[ false == \t\r\u\e ]]
+ [[ ! -z '' ]]
```

**Comment by camaeel** [comment]
@rjsadow, @dims @reetasingh 
Hi, any chance for review and approval? Or something is still missing before it can be successfully reviewed?

**Review by BenTheElder — COMMENTED** [review]
/lgtm

**Pull request merged**
