### PR TITLE
Refactor into stateful types and remove viper dependency from pkg/ code

### LINKED ISSUE #175: Confusing configuration file
Suppose you download Hydrophone and put it somewhere in your `PATH`. You navigate to your project of choice and take a look:

```bash
$ cd ~/myproject
$ hydrophone --help
...
      --output-dir string           directory for logs. (default "/home/xrstf/myproject")
...
```

Cool! So you run it to perform conformance tests:

```bash
$ export KUBECONFIG=...
$ hydrophone --conformance
...
13:30:53 INF Downloading e2e.log to /home/xrstf/myproject/e2e.log...
13:30:53 INF Downloading junit_01.xml to /home/xrstf/myproject/junit_01.xml...
```

Cool! Now let's run the conformance tests for another project:

```bash
$ cd ..
$ cd anotherproject
$ hydrophone --help
...
      --output-dir string           directory for logs. (default "/home/xrstf/anotherproject")
...

$ export KUBECONFIG=...
$ hydrophone --conformance
...
13:30:53 INF Downloading e2e.log to /home/xrstf/myproject/e2e.log...
13:30:53 INF Downloading junit_01.xml to /home/xrstf/myproject/junit_01.xml...
```

And now you'd be confused why your files ended up in a different location.

I think the way a config file works should be handled differently. Silently remembering default values that are path-dependent is IMHO not a good idea. I would never expect a tool to just take my current flags and use them for all future invocations if I don't specify a flag. Especially since I have no real way to opt out of this behaviour.

### PR DESCRIPTION
**Pull request by xrstf**
This started out as a simple "remove the viper.WriteConfig line" PR and then slowly escalated over the last few hours.

My main goal here was to fix #175 and my idea was to introduce a `Configuration` struct that we can pass into othe components, instead of making the entire codebase rely on global state and `viper.String()` calls.

However, mapping pflags via viper to a config file makes it, as far as I could see, impossible to keep the `Configuration` struct I was aiming for. When using viper, the whole "load the config file, merge it with CLI flags" logic is based around the idea that you then use `viper.Get...` to retrieve the merged data. Viper will not (AFAIK) write the merged data back into the struct.

So instead of using Viper to map the flags, I hand rolled a bit of code to load a YAML file and merge the flags with it. As discussed in #175, the logic is:

* if something is explicitly given via CLI flag, that has priority.
* if not, if a config file was given explicitly via `--config`, it is loaded and the value in the config file is used if not empty.
* if there is no config file or the value in the config file is empty, then the hydrophone default value is used.

The config file is never written to by hydrophone. Users have to manually create one if they want to use it.

Importantly, the 3 different run modes (cleanup, list-images, conformance[/--focus]) are not part of the Configuration, as they only serve a purpose in the root command to distinguish which code to call. Personally I would even remove Verbosity, DryRun and Parallel from the config file, but it doesn't hurt to have them there either.

---

Once the config was turned into a struct, I proceeded to get rid of some `init()` functions to reduce overall global state. What previously were global static functions like `service.Cleanup` are now functions on a `TestRunner` struct, which holds the necessary dependencies (and, importantly, gets the Configuration injected).

The `service` package was renamed to `conformance`, as the package implements running the Kubernetes conformance suite. The client to access the results was moved to `pkg/conformance/client`.

Lots of code from the `common` package was moved into a new `types` package, type-ical for Kubernetes projects. :grin: 

The recently introduced ImagePullBackoff check was moved into a CreatePod() helper function that now simply waits for the Pod to be running before continuing.

---

One thing lead to another and now half the codebase was moved around :grimacing:

### CODE REVIEW

**Comment by rakshitgondwal** [comment]
Thanks for this, it is going to take a little while to review this whole, but even I was thinking what could be the best way to fix the issue with viper.
One thing I thought about was to just use `WriteConfig()` instead of `SafeWriteConfig()` which would lead to an overwrite of config file everytime. But then another thing came up that do we actually need Viper? why don't we just make the flag variables as global and reference them across, not sure if this would be a tidy method though.

But still I'll have a look at your approach :)

**Comment by xrstf** [comment]
> why don't we just make the flag variables as global and reference them across

Global variables make it extremely hard to understand data flow and make it uneccessarily complicated to re-use / test code. Calling `viper.String()` everywhere is just as bad as having a global variable. Hydrophone's code was already sprinkled with init() functions that made it complicated to follow what's going on. I don't think adding even _more_ global state would help the codebase.

> One thing I thought about was to just use WriteConfig() instead of SafeWriteConfig() which would lead to an overwrite of config file everytime.

And what is the point then to overwrite the config file everytime? In what scenario would that be desirable? If I don't specify a --config flag, I _do not want to use a config file_. If I _do_ specify the --config flag, then please do not fiddle with it and overwrite it. :D I might have mounted it from a ConfigMap or run in a read-only filesystem.

Even if you overwrite the config file every single time, you are still remembering the last settings/flags and re-using them for the next run of hydrophone. So we would still diverge from what is shown as default in --help and what is _actually_ the "default".

**Pull request merged**
