### PR TITLE
Update to latest Kubernetes dependencies

### PR DESCRIPTION
**Pull request by dims**
Ran [bump-k8s.sh](https://github.com/kubernetes-sigs/hydrophone/blob/main/hack/bump-k8s.sh)

### CODE REVIEW

**Comment by rjsadow** [comment]
/lgtm
I thought we had some automation for bumping this.

**Comment by dims** [comment]
automation broke when kubernetes github org moved ... https://github.com/kubernetes/org/issues/5126#issuecomment-2350687894

**Pull request merged**
