### PR TITLE
Add reetasingh as reviewer

### PR DESCRIPTION
**Pull request by reetasingh**

### CODE REVIEW

**Comment by reetasingh** [comment]
@rjsadow

**Comment by rjsadow** [comment]
/ok-to-test
/lgtm
/approve
:tada:  Thanks Reeta!

**Comment by rjsadow** [comment]
Hey @reetasingh, I'm not sure why the `/verify-owners` test isn't working. Can you please rebase and repush?

**Comment by reetasingh** [comment]
> Hey @reetasingh, I'm not sure why the `/verify-owners` test isn't working. Can you please rebase and repush?

Hi @rjsadow I am a member of kubernetes-sig now, mind giving /lgtm again?

**Pull request merged**
