### PR TITLE
feat: allow to customize the namespace

### PR DESCRIPTION
**Pull request by vbehar**
add a new `-namespace` flag to set a custom namespace - no impact for existing users, because we keep the same default value

### CODE REVIEW

**Comment by rjsadow** [comment]
Hey @vbehar! Thanks for the PR. I would like to wait until we land #120 before adding the namespace flag as it'll significantly change the way we're handling flags and the config. 

Cc @rakshitgondwal

**Comment by vbehar** [comment]
ok sure.

**Comment by rjsadow** [comment]
Hey @vbehar We should be good now with our flags structure. Are you ok to rework this PR a bit to fit the new model? If you need any help or have questions feel free to reach out to @rakshitgondwal or I on slack, or in the #hydrophone channel.

**Comment by vbehar** [comment]
> Hey @vbehar We should be good now with our flags structure. Are you ok to rework this PR a bit to fit the new model? If you need any help or have questions feel free to reach out to @rakshitgondwal or I on slack, or in the #hydrophone channel.

yes, I'll do it today or tomorrow

**Comment by vbehar** [comment]
I'm closing this one, see https://github.com/kubernetes-sigs/hydrophone/pull/139 instead (rebased against main)

**Pull request closed without merging**
